import argparse
import json
from pathlib import Path
from urllib.parse import urlencode
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description='Summary controls browser regressions against the running Vite server.')
parser.add_argument('--base-url', default='http://localhost:5173')
parser.add_argument('--plugin-dir', type=Path, default=ROOT.parent / 'ChattyPop-Plugins-Public/plugins/summaries')
parser.add_argument('--screenshots-dir', type=Path)
args = parser.parse_args()
URL = args.base_url.rstrip('/') + '/@fs/' + (ROOT / 'tests/browser/summaryControls.html').as_posix() + '?' + urlencode({'plugin': args.plugin_dir.resolve().as_posix()})

def capture(page, name):
    if args.screenshots_dir:
        args.screenshots_dir.mkdir(parents=True, exist_ok=True)
        page.screenshot(path=str(args.screenshots_dir / name))
checks = []
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={'width': 375, 'height': 667})
    page.set_default_timeout(5000)
    page.goto(URL + '&mobile=1')
    trigger = page.get_by_role('button', name='Summary options', exact=True)
    trigger.click()
    dialog = page.locator('dialog')
    expect(dialog).to_be_visible()
    assert page.evaluate("(() => {const r=document.querySelector('dialog').getBoundingClientRect();return r.x===0&&r.y===0&&r.width===innerWidth&&r.height===innerHeight&&document.activeElement.tagName==='DIV'})()")
    checks.append('Mobile: full screen, modal focus lands on surface')
    page.get_by_label('Time frame', exact=True).select_option('today')
    page.get_by_role('button', name='Close summary options').click()
    expect(dialog).to_have_count(0)
    trigger.click()
    expect(page.get_by_label('Time frame', exact=True)).to_have_value('today')
    checks.append('Mobile: selected time frame survives sheet removal')
    channel = page.get_by_role('button', name='Channels: Everything', exact=True)
    assert channel.evaluate("b=>getComputedStyle(b).fontSize===getComputedStyle(document.querySelector('select[id$=\"-provider\"]')).fontSize")
    channel.click()
    picker = page.get_by_role('dialog', name='Channels', exact=True)
    expect(picker).to_be_visible()
    expect(page.locator(':popover-open')).to_have_count(0)
    assert page.evaluate("document.activeElement.tagName === 'DIV'")
    expect(picker.get_by_role('combobox', name='Filter channels')).not_to_be_focused()
    assert picker.get_by_role('listbox').evaluate('(l)=>l.scrollHeight>l.clientHeight')
    expect(picker.get_by_role('option', name='Everything', exact=True)).to_have_attribute('aria-selected', 'true')
    expect(picker.get_by_role('listbox', name='Channels', exact=True)).to_be_visible()
    checks.append('Mobile: full-screen channel page, neutral focus, labeled search/list, current check and independent scroll')
    picker.get_by_role('button', name='Back from Channels').click()
    expect(picker).to_have_count(0)
    expect(channel).to_be_focused()
    expect(page.get_by_label('Time frame', exact=True)).to_have_value('today')
    channel.click()
    page.get_by_role('option', name='general', exact=True).click()
    expect(picker).to_have_count(0)
    expect(page.get_by_role('button', name='Channels: general')).to_be_focused()
    expect(page.get_by_label('Time frame', exact=True)).to_have_value('today')
    checks.append('Mobile: Back preserves choice; row selection returns to the options form and preserves range')
    page.get_by_role('button', name='Channels: general').click()
    search = picker.get_by_role('combobox', name='Filter channels')
    search.click()
    page.evaluate("document.documentElement.style.setProperty('--cp-keyboard-inset','300px')")
    assert picker.evaluate("d=>d.getBoundingClientRect().bottom===innerHeight-300&&d.querySelector('ul').getBoundingClientRect().bottom<=innerHeight-300")
    search.fill('Review person 3')
    expect(picker.get_by_role('option', name='Review person 3', exact=True)).to_be_visible()
    capture(page, 'summary-channels-keyboard.png')
    # Assistive activation may dispatch click without a preceding mouse press.
    picker.get_by_role('option', name='Review person 3', exact=True).evaluate('(e)=>e.click()')
    expect(picker).to_have_count(0)
    expect(page.get_by_role('button', name='Channels: Review person 3')).to_be_focused()
    checks.append('Mobile: keyboard clears filter/list; search finds hidden DMs; click-only activation selects')
    # Exaggerated duration exposes delayed return even though static-inset checks pass.
    timing = page.evaluate("""async () => {
      const root=document.documentElement, parent=document.querySelector('dialog');
      const run=parent.querySelector('[data-variant=primary]');
      root.style.setProperty('--cp-keyboard-duration','600ms');
      root.style.setProperty('--cp-keyboard-inset','0px');
      const samples=[];
      const sample=()=>samples.push({inset:parseFloat(getComputedStyle(root).getPropertyValue('--cp-keyboard-inset')),height:parent.getBoundingClientRect().height,bottom:run.getBoundingClientRect().bottom});
      await new Promise(requestAnimationFrame); sample();
      for(const animation of root.getAnimations()) await animation.finished;
      sample(); root.style.setProperty('--cp-keyboard-duration','0ms');
      return {samples, viewport:innerHeight};
    }""")
    assert timing['samples'][0]['inset'] > 0
    assert all(sample['height'] == timing['viewport'] for sample in timing['samples'])
    assert timing['samples'][0]['bottom'] == timing['samples'][-1]['bottom']
    checks.append('Mobile: returning from search pins Run while the keyboard inset is still animating closed')
    page.evaluate("document.documentElement.style.setProperty('--cp-keyboard-inset','0px')")
    page.get_by_role('button', name='Channels: Review person 3').click()
    expect(picker.get_by_role('option', name='Review person 3', exact=True)).to_have_attribute('aria-selected', 'true')
    picker.get_by_role('option', name='Show all 3', exact=True).click()
    expect(picker.get_by_role('option', name='Review person 0', exact=True)).to_be_visible()
    assert page.evaluate("document.activeElement.tagName !== 'INPUT'")
    page.keyboard.press('Escape')
    expect(picker).to_have_count(0)
    expect(page.get_by_role('dialog', name='Summary options')).to_be_visible()
    page.keyboard.press('Escape')
    expect(dialog).to_have_count(0)
    expect(trigger).to_be_focused()
    checks.append('Mobile: hidden-tail expansion stays keyboard-free; Escape dismisses child before parent')
    trigger.click()
    page.get_by_role('button', name='Channels: Review person 3').click()
    page.evaluate("document.querySelector('dialog').close()")
    expect(dialog).to_have_count(0)
    expect(page.locator(':popover-open')).to_have_count(0)
    checks.append('Mobile: parent native close disposes its portaled child dialog')
    trigger.click()
    capture(page, 'summary-options-mobile.png')
    # Full-screen pages use explicit close rather than the old sheet pull.
    page.evaluate("(() => {const d=document.querySelector('dialog');const touch=(type,y)=>d.dispatchEvent(new TouchEvent(type,{bubbles:true,cancelable:true,touches:type==='touchend'?[]:[new Touch({identifier:1,target:d,clientX:50,clientY:y})]}));touch('touchstart',200);touch('touchmove',400);touch('touchend',400)})()")
    expect(dialog).to_be_visible()
    assert page.evaluate("!document.querySelector('dialog').style.translate")
    checks.append('Mobile: grabber/pull convention removed from full-screen options')
    page.set_viewport_size({'width': 320, 'height': 280})
    assert page.evaluate("(async()=>{const d=document.querySelector('dialog'),b=d.querySelector('div[class*=runBody]'),c=d.querySelector('[aria-label=\"Close summary options\"]');const before=c.getBoundingClientRect().top;b.scrollTop=b.scrollHeight;await new Promise(requestAnimationFrame);const r=d.getBoundingClientRect();return r.y===0&&r.height===innerHeight&&b.scrollTop>0&&c.getBoundingClientRect().top===before&&d.querySelector('[data-variant=primary]').getBoundingClientRect().bottom<=innerHeight})()")
    checks.append('Mobile: short screen scrolls fields and keeps close visible')
    page.get_by_role('button', name='Close summary options').click()
    page.set_viewport_size({'width': 375, 'height': 667})
    page.evaluate("document.documentElement.style.setProperty('--cp-keyboard-inset','220px')")
    trigger.click()
    assert page.evaluate("document.querySelector('dialog').getBoundingClientRect().bottom === innerHeight")
    checks.append('Mobile: parent remains full-screen while the picker owns keyboard clearance')
    page.get_by_role('button', name='Channels: Review person 3', exact=True).click()
    page.evaluate('window.reviewDispose()')
    expect(dialog).to_have_count(0)
    expect(page.locator(':popover-open')).to_have_count(0)
    assert page.evaluate('window.reviewErrors') == []
    checks.append('Mobile: disposal clears modal and nested flyout')

    page.set_viewport_size({'width': 1280, 'height': 800})
    page.goto(URL)
    expect(trigger).to_be_visible()
    page.evaluate("(() => {window.reviewRAF=new Set();const raf=window.requestAnimationFrame.bind(window),cancel=window.cancelAnimationFrame.bind(window);window.requestAnimationFrame=fn=>{let id=raf(t=>{window.reviewRAF.delete(id);fn(t)});window.reviewRAF.add(id);return id};window.cancelAnimationFrame=id=>{window.reviewRAF.delete(id);cancel(id)}})()")
    trigger.click()
    panel = page.locator('[role=dialog]')
    expect(panel).to_be_visible()
    expect(panel).to_be_focused()
    page.get_by_label('Provider', exact=True).click()
    page.keyboard.press('Escape')
    expect(panel).to_be_visible()
    capture(page, 'summary-options-desktop.png')
    checks.append('Desktop: surface focus; closing native provider picker preserves panel')
    page.evaluate("document.getElementById('root').style.paddingTop='100px'")
    assert page.evaluate("(async()=>{await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);const p=document.querySelector('[role=dialog]'),t=document.querySelector('[aria-label=\"Summary options\"]');return p.getBoundingClientRect().top===t.getBoundingClientRect().bottom+parseFloat(getComputedStyle(p).getPropertyValue('--cp-popover-gap'))&&!document.getElementById('root').contains(p)})()")
    checks.append('Desktop: portal avoids header ownership; panel follows moved trigger')
    page.get_by_role('button', name='Channels: Everything', exact=True).click()
    page.evaluate("document.querySelector('[role=dialog]').hidePopover()")
    expect(trigger).to_have_attribute('aria-expanded', 'false')
    expect(page.locator(':popover-open')).to_have_count(0)
    assert page.evaluate('window.reviewRAF.size') == 0
    checks.append('Desktop: native dismissal removes child picker and stops tracking')
    trigger.click()
    page.get_by_role('button', name='Channels: Everything', exact=True).click()
    page.keyboard.press('Escape')
    expect(panel).to_be_visible()
    page.keyboard.press('Escape')
    expect(panel).not_to_be_visible()
    expect(trigger).to_be_focused()
    checks.append('Desktop: Escape dismisses nested picker before parent')
    trigger.click()
    page.evaluate("document.body.insertAdjacentHTML('beforeend','<button id=outside style=\"position:fixed;left:500px;top:500px\">Outside</button>')")
    page.get_by_role('button', name='Outside').click()
    expect(panel).not_to_be_visible()
    expect(page.locator('#outside')).to_be_focused()
    checks.append('Desktop: outside click dismisses without stealing focus')
    trigger.click()
    page.get_by_role('button', name='Channels: Everything', exact=True).click()
    search = page.get_by_role('combobox', name='Filter channels')
    expect(search).to_be_focused()
    search.fill('general')
    page.keyboard.press('ArrowDown')
    page.keyboard.press('Enter')
    expect(page.get_by_role('button', name='Channels: general')).to_be_focused()
    expect(panel).to_be_visible()
    expect(page.locator(':popover-open')).to_have_count(1)
    checks.append('Desktop: auto-focused search, grouped filtering and keyboard selection preserve parent')
    page.get_by_role('button', name='Channels: general').click()
    search.fill('no-such-channel')
    page.keyboard.press('Enter')
    expect(search).to_be_visible()
    expect(page.get_by_text('No matches', exact=True)).to_be_visible()
    search.fill('')
    dm = page.get_by_role('option', name='Direct messages', exact=True)
    dm.dispatch_event('mousedown', {'button': 0})
    expect(search).to_be_visible()
    page.get_by_role('option', name='Show all 4', exact=True).click()
    expect(search).to_be_focused()
    expect(page.get_by_role('option', name='Review person 0', exact=True)).to_be_visible()
    page.get_by_role('option', name='Everything', exact=True).evaluate('(e)=>e.click()')
    expect(page.get_by_role('button', name='Channels: Everything')).to_be_focused()
    expect(panel).to_be_visible()
    checks.append('Desktop: empty matches, mouse-press safety, tail expansion and click-only activation')
    page.set_viewport_size({'width': 320, 'height': 200})
    assert page.evaluate("(async()=>{await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);const r=document.querySelector('[role=dialog]').getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth&&r.bottom<=innerHeight})()")
    page.evaluate('window.reviewDispose()')
    expect(page.locator(':popover-open')).to_have_count(0)
    assert page.evaluate('window.reviewRAF.size') == 0
    assert page.evaluate('window.reviewErrors') == []
    checks.append('Desktop: viewport clamping and disposal cleanup')
    browser.close()
print(json.dumps({'passed': len(checks), 'checks': checks}, indent=2))
